//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.commanigy.com", ClrNamespace="schemas.commanigy.com")]

namespace schemas.commanigy.com
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadMeta", Namespace="http://schemas.commanigy.com")]
    public partial class UploadMeta : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.commanigy.com", ConfigurationName="ITransfer")]
public interface ITransfer
{
    
    // CODEGEN: Generating message contract since the operation Upload is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.commanigy.com/ITransfer/Upload", ReplyAction="http://schemas.commanigy.com/ITransfer/UploadResponse")]
    UploadResponse Upload(UploadMessage request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://schemas.commanigy.com/ITransfer/SharePackage", ReplyAction="http://schemas.commanigy.com/ITransfer/SharePackageResponse")]
    string SharePackage(string sender, string[] recipients, string packageCode, string[] tokens, string subject, string message);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UploadMessage", WrapperNamespace="http://schemas.commanigy.com", IsWrapped=true)]
public partial class UploadMessage
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.commanigy.com")]
    public schemas.commanigy.com.UploadMeta Meta;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.commanigy.com", Order=0)]
    public System.IO.Stream Content;
    
    public UploadMessage()
    {
    }
    
    public UploadMessage(schemas.commanigy.com.UploadMeta Meta, System.IO.Stream Content)
    {
        this.Meta = Meta;
        this.Content = Content;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UploadResponse
{
    
    public UploadResponse()
    {
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITransferChannel : ITransfer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TransferClient : System.ServiceModel.ClientBase<ITransfer>, ITransfer
{
    
    public TransferClient()
    {
    }
    
    public TransferClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TransferClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TransferClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TransferClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UploadResponse ITransfer.Upload(UploadMessage request)
    {
        return base.Channel.Upload(request);
    }
    
    public void Upload(schemas.commanigy.com.UploadMeta Meta, System.IO.Stream Content)
    {
        UploadMessage inValue = new UploadMessage();
        inValue.Meta = Meta;
        inValue.Content = Content;
        UploadResponse retVal = ((ITransfer)(this)).Upload(inValue);
    }
    
    public string SharePackage(string sender, string[] recipients, string packageCode, string[] tokens, string subject, string message)
    {
        return base.Channel.SharePackage(sender, recipients, packageCode, tokens, subject, message);
    }
}
